# Generated by Django 5.2.17 on 2026-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaliHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(db_index=True)),
                ('impact', models.CharField(choices=[('shutdown', 'Island shutdown - nobody travels'), ('no_staff', 'Staff generally unavailable'), ('reduced', 'Reduced staff availability'), ('info', 'Worth knowing, no staffing impact')], default='info', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bali holiday',
                'verbose_name_plural': 'Bali holidays',
                'ordering': ['date'],
                'unique_together': {('name', 'date')},
            },
        ),
    ]
