# Generated by Django 5.2.17 on 2026-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, help_text='WhatsApp number, international format.', max_length=32)),
                ('nationality', models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2. Required for the STM police report.', max_length=2)),
                ('preferred_language', models.CharField(blank=True, max_length=5)),
                ('total_stays', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal. Never shown to the guest.')),
                ('retain_until', models.DateField(blank=True, help_text='Delete or anonymise this record after this date.', null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='GuestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('portal_opened', 'Opened their page'), ('request_made', 'Asked for something'), ('experience_viewed', 'Looked at a local activity'), ('experience_booked', 'Booked a local activity'), ('feedback_given', 'Left private feedback'), ('message_sent', 'Sent a message')], db_index=True, max_length=32)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'guest activity',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='1 to 5.')),
                ('comment', models.TextField(blank=True)),
                ('escalated_to_owner', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'guest feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('cleaning', 'Cleaning'), ('repair', 'Something is broken'), ('chef', 'Private chef'), ('groceries', 'Grocery stocking'), ('transfer', 'Airport transfer'), ('other', 'Something else')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen by staff'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When staff were actually messaged.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
