# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_initial'),
        ('guests', '0001_initial'),
        ('organizations', '0001_initial'),
        ('villas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='guestactivity',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='guestactivity',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='guestactivity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='guestactivity',
            name='villa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_activity', to='villas.villa'),
        ),
        migrations.AddField(
            model_name='guestfeedback',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='guestfeedback',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='guestfeedback',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['organization', 'nationality'], name='guests_gues_organiz_4687dd_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['organization', 'email'], name='guests_gues_organiz_91f122_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['organization', 'phone'], name='guests_gues_organiz_6c61b3_idx'),
        ),
        migrations.AddIndex(
            model_name='guestactivity',
            index=models.Index(fields=['organization', 'kind', 'occurred_at'], name='guests_gues_organiz_d8e3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='guestactivity',
            index=models.Index(fields=['guest', 'occurred_at'], name='guests_gues_guest_i_aa3756_idx'),
        ),
    ]
