# Generated by Django 5.2.17 on 2026-08-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='nationality',
            field=models.CharField(blank=True, choices=[('ID', 'Indonesian'), ('AU', 'Australian'), ('US', 'American'), ('GB', 'British'), ('DE', 'German'), ('FR', 'French'), ('NL', 'Dutch'), ('RU', 'Russian'), ('JP', 'Japanese'), ('KR', 'South Korean'), ('SG', 'Singaporean'), ('MY', 'Malaysian'), ('CN', 'Chinese'), ('HK', 'Hong Kong'), ('TW', 'Taiwanese'), ('IN', 'Indian'), ('PH', 'Filipino'), ('TH', 'Thai'), ('VN', 'Vietnamese'), ('CA', 'Canadian'), ('ES', 'Spanish'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('SE', 'Swedish'), ('NO', 'Norwegian'), ('DK', 'Danish'), ('FI', 'Finnish'), ('CH', 'Swiss'), ('AT', 'Austrian'), ('BE', 'Belgian'), ('IE', 'Irish'), ('PL', 'Polish'), ('BR', 'Brazilian'), ('MX', 'Mexican'), ('AR', 'Argentinian'), ('ZA', 'South African'), ('NZ', 'New Zealander'), ('AE', 'Emirati'), ('SA', 'Saudi Arabian'), ('IL', 'Israeli'), ('TR', 'Turkish'), ('UA', 'Ukrainian')], db_index=True, help_text='ISO 3166-1 alpha-2. Required for the STM police report.', max_length=2),
        ),
    ]
