# Generated by Django 5.2.17 on 2026-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('nib', 'Business licence (NIB)'), ('pbg', 'Building approval (PBG)'), ('slf', 'Building safety certificate (SLF)'), ('tax', 'Tax registration'), ('other', 'Other document')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(upload_to='compliance/%Y/')),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, db_index=True, null=True)),
                ('reminder_days', models.PositiveSmallIntegerField(default=60, help_text='Start warning this many days before it runs out.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['expires_on'],
            },
        ),
        migrations.CreateModel(
            name='PoliceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(db_index=True, help_text='24 hours after arrival, Bali time.')),
                ('status', models.CharField(choices=[('needed', 'Still to do'), ('filed', 'Marked as done by staff'), ('not_required', 'Not needed')], default='needed', max_length=20)),
                ('marked_done_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'police report reminder',
                'ordering': ['deadline'],
            },
        ),
    ]
