# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_initial'),
        ('compliance', '0001_initial'),
        ('guests', '0001_initial'),
        ('organizations', '0001_initial'),
        ('villas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='villa',
            field=models.ForeignKey(blank=True, help_text='Leave empty if it covers the whole business.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='villas.villa'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_reports', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_reports', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='marked_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_reports_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policereport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
    ]
