# Generated by Django 5.2.17 on 2026-08-28 14:17, hand-edited to backfill
# ComplianceDocument.kind into the new ComplianceDocumentType catalog before
# dropping the old field - see apps/compliance/models.py's docstring on
# ComplianceDocumentType for why the 5 default types leave
# default_validity_days blank rather than guessing real permit durations.

import django.db.models.deletion
from django.db import migrations, models

GLOBAL_TYPES = {
    "nib": "Business licence (NIB)",
    "pbg": "Building approval (PBG)",
    "slf": "Building safety certificate (SLF)",
    "tax": "Tax registration",
    "other": "Other document",
}


def create_types_and_backfill(apps, schema_editor):
    ComplianceDocumentType = apps.get_model("compliance", "ComplianceDocumentType")
    ComplianceDocument = apps.get_model("compliance", "ComplianceDocument")

    types_by_kind = {}
    for kind, name in GLOBAL_TYPES.items():
        types_by_kind[kind], _created = ComplianceDocumentType.objects.get_or_create(
            organization=None, name=name, defaults={"default_reminder_days": 60},
        )

    for document in ComplianceDocument.objects.all():
        document.document_type = types_by_kind[document.kind]
        document.save(update_fields=["document_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_initial'),
        ('organizations', '0003_organization_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('template_file', models.FileField(blank=True, help_text='A blank template staff can download and fill in.', null=True, upload_to='compliance/templates/')),
                ('default_validity_days', models.PositiveIntegerField(blank=True, help_text="How long this document is normally valid for, used to suggest an expiry date. Leave blank if it doesn't expire.", null=True)),
                ('default_reminder_days', models.PositiveSmallIntegerField(default=60, help_text='Start warning this many days before it runs out.')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Leave empty for a type available to every client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_document_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='compliance.compliancedocumenttype'),
        ),
        migrations.RunPython(create_types_and_backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='compliancedocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='compliance.compliancedocumenttype'),
        ),
        migrations.RemoveField(
            model_name='compliancedocument',
            name='kind',
        ),
    ]
