# Generated by Django 5.2.17 on 2026-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=160)),
                ('name_id', models.CharField(blank=True, max_length=160)),
                ('description_en', models.TextField(blank=True)),
                ('description_id', models.TextField(blank=True)),
                ('operator_name', models.CharField(blank=True, max_length=160)),
                ('operator_phone', models.CharField(blank=True, max_length=32)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='What the local operator pays the villa owner.', max_digits=5)),
                ('photo', models.ImageField(blank=True, upload_to='experiences/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='RateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='IDR', help_text='ISO 4217 code, exactly as the source reported it.', max_length=3)),
                ('channel', models.CharField(max_length=20)),
                ('stay_date', models.DateField(db_index=True)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-stay_date'],
            },
        ),
    ]
