# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('organizations', '0001_initial'),
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='experience',
            name='villas',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='villas.villa'),
        ),
        migrations.AddField(
            model_name='ratesnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='ratesnapshot',
            name='villa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_snapshots', to='villas.villa'),
        ),
        migrations.AddIndex(
            model_name='ratesnapshot',
            index=models.Index(fields=['organization', 'villa', 'stay_date'], name='marketing_r_organiz_24f8ff_idx'),
        ),
    ]
