# Generated by Django 5.2.17 on 2026-09-02 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
        ('organizations', '0006_remove_membership_role'),
        ('villas', '0014_schedule_photo_sweep'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest_count', models.PositiveSmallIntegerField(default=1)),
                ('guest_name', models.CharField(max_length=160)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, help_text='WhatsApp number, if they left one.', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('quoted_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_handled', models.BooleanField(default=False, help_text='Someone has replied to this.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator')),
                ('room_category', models.ForeignKey(blank=True, help_text='Which room type the visitor was looking at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_enquiries', to='villas.roomcategory')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_enquiries', to='villas.villa')),
            ],
            options={
                'verbose_name_plural': 'booking enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'villa', 'check_in'], name='marketing_b_organiz_660d59_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='enquiry_checkout_after_checkin')],
            },
        ),
    ]
