# Generated by Django 5.2.17 on 2026-09-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_seed_bamboo_loft_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
