# Generated by Django 5.2.17 on 2026-09-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_experience_commission_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_id',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
