# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('beds24', 'Beds24'), ('ical', 'Calendar link')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('beds24_property_id', models.CharField(blank=True, max_length=60)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
                ('ical_url', models.URLField(blank=True)),
                ('ical_channel', models.CharField(blank=True, help_text='Which site this feed comes from.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator')),
                ('villa', models.ForeignKey(blank=True, help_text='iCal feeds are per villa. A Beds24 account covers many.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_accounts', to='villas.villa')),
            ],
            options={
                'ordering': ['provider', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(blank=True, max_length=120)),
                ('body', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='sync.syncaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('webhook', 'Pushed by the source'), ('scheduled', 'Routine check'), ('manual', 'Started by hand')], max_length=20)),
                ('result', models.CharField(choices=[('ok', 'Worked'), ('partial', 'Partly worked'), ('failed', 'Failed')], max_length=20)),
                ('bookings_created', models.PositiveIntegerField(default=0)),
                ('bookings_updated', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sync.syncaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
