# Generated by Django 5.2.17 on 2026-08-26 18:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField(db_index=True)),
                ('guest_count', models.PositiveSmallIntegerField(default=1)),
                ('channel', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking_com', 'Booking.com'), ('direct', 'Direct'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('blocked', 'Not available')], default='confirmed', max_length=20)),
                ('source_detail', models.CharField(choices=[('full', 'Full details'), ('dates_only', 'Dates only'), ('manual', 'Entered by staff')], default='dates_only', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='IDR', help_text='ISO 4217 code, exactly as the source reported it.', max_length=3)),
                ('kind', models.CharField(choices=[('payout', 'Paid by the booking site'), ('direct', 'Paid directly'), ('deposit', 'Deposit'), ('refund', 'Refund')], default='payout', max_length=20)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('is_outstanding', models.BooleanField(default=False, help_text='Still owed - shows on the daily staff view.')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-received_on'],
            },
        ),
    ]
