# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, help_text='Absent on calendar-only bookings - the feed carries no name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='guests.guest'),
        ),
    ]
