# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('organizations', '0001_initial'),
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='booking',
            name='villa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='villas.villa'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organization', 'check_in', 'check_out'], name='bookings_bo_organiz_3db938_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'external_id'), name='unique_external_booking_per_org'),
        ),
    ]
