# Generated by Django 5.2.17 on 2026-08-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('villas', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, help_text="Optional - only set once a villa's rooms are defined individually.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='villas.room'),
        ),
    ]
