# Generated by Django 5.2.17 on 2026-08-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_backfill_booking_rooms'),
        ('villas', '0004_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, help_text="Optional - only set once a villa's rooms are defined individually. PROTECT (not SET_NULL) on purpose: the calendar only draws bookings on room rows, so a booking silently losing its room would silently disappear from view - see apps/bookings/services.py's build_calendar_rows().", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='villas.room'),
        ),
    ]
