# Generated by Django 5.2.17 on 2026-08-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nightly_rate',
            field=models.PositiveBigIntegerField(blank=True, help_text='Price for one night, in rupiah, agreed for this stay.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='channel',
            field=models.CharField(choices=[('airbnb', 'Airbnb'), ('booking_com', 'Booking.com'), ('direct', 'Direct'), ('whatsapp', 'WhatsApp'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
