# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(help_text="Used in the villa's public web address.")),
                ('area', models.CharField(blank=True, help_text='Canggu, Ubud, Uluwatu, Seminyak.', max_length=80)),
                ('address', models.TextField(blank=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('description_en', models.TextField(blank=True)),
                ('description_id', models.TextField(blank=True)),
                ('is_listed_publicly', models.BooleanField(default=False, help_text="Show this villa's own web page and direct booking.")),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=80)),
                ('name_id', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('villas', models.ManyToManyField(blank=True, related_name='amenities', to='villas.villa')),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='VillaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='villas/%Y/%m/')),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('caption_id', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='villas.villa')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
