# Generated by Django 5.2.17 on 2026-08-27 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='base_nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Indicative rate only, in the operator's own reporting currency. Real prices per booking live on the booking itself.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='villa',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='villa',
            name='check_out_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AddField(
            model_name='villa',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Paste a Google Maps link so staff and guests can find it.'),
        ),
        migrations.AddField(
            model_name='villa',
            name='min_nights',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='villa',
            name='property_type',
            field=models.CharField(choices=[('villa', 'Villa'), ('guesthouse', 'Guesthouse'), ('apartment', 'Apartment'), ('house', 'House')], default='villa', max_length=20),
        ),
        migrations.AddField(
            model_name='villa',
            name='size_sqm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='size (m²)'),
        ),
    ]
