# Generated by Django 5.2.17 on 2026-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_villa_base_nightly_rate_villa_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='base_monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For long-stay guests. Same currency as the nightly rate.', max_digits=14, null=True),
        ),
    ]
