# Generated by Django 5.2.17 on 2026-08-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_plan'),
        ('villas', '0009_alter_room_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='villas',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='base_monthly_rate',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='base_nightly_rate',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='min_nights',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='size_sqm',
        ),
        migrations.AddField(
            model_name='amenity',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Leave empty for an amenity every operator can pick.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='room_categories', to='villas.amenity'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='max_guests',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='minimum_nights',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='monthly_rate',
            field=models.PositiveBigIntegerField(blank=True, help_text='Price for a whole month, in rupiah.', null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='nightly_rate',
            field=models.PositiveBigIntegerField(blank=True, help_text='Price for one night, in rupiah.', null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='size_sqm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='size (m²)'),
        ),
        migrations.AddField(
            model_name='villa',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoomCategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='room-types/%Y/%m/')),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('caption_id', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='villas.roomcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='operator')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
