# Generated by Django 5.2.17 on 2026-09-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0011_seed_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategoryphoto',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='Uploaded but not saved yet - discarded if the page is left.'),
        ),
        migrations.AddField(
            model_name='roomcategoryphoto',
            name='pending_delete',
            field=models.BooleanField(default=False, help_text='Taken off the form but not saved yet - kept until Save.'),
        ),
        migrations.AddField(
            model_name='villaphoto',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='Uploaded but not saved yet - discarded if the page is left.'),
        ),
        migrations.AddField(
            model_name='villaphoto',
            name='pending_delete',
            field=models.BooleanField(default=False, help_text='Taken off the form but not saved yet - kept until Save.'),
        ),
    ]
