# Generated by Django 5.2.17 on 2026-09-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0012_roomcategoryphoto_is_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='use_first_category_photos',
            field=models.BooleanField(default=False, help_text="Show the first room type's photos here instead of its own."),
        ),
    ]
