# Generated by Django 5.2.17 on 2026-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0015_seed_amenity_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategoryphoto',
            name='crop_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomcategoryphoto',
            name='crop_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomcategoryphoto',
            name='crop_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomcategoryphoto',
            name='crop_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villaphoto',
            name='crop_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villaphoto',
            name='crop_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villaphoto',
            name='crop_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villaphoto',
            name='crop_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
