# Generated by Django 5.2.17 on 2026-09-03 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0016_roomcategoryphoto_crop_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='discount_enabled',
            field=models.BooleanField(default=False, help_text="Apply the coupon discount to this room type's rates."),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Coupon discount, as a percentage of the rate.', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
