# Generated by Django 5.2.17 on 2026-09-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0017_roomcategory_discount_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='villas', to='villas.amenity'),
        ),
    ]
