# Generated by Django 5.2.17 on 2026-09-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0018_villa_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='auto_reassign_rooms',
            field=models.BooleanField(default=False, help_text='Move upcoming bookings between rooms of the same type so longer stays can fit.'),
        ),
    ]
