# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='villas',
            field=models.ManyToManyField(blank=True, help_text='Staff only. Leave empty for access to every villa.', related_name='assigned_members', to='villas.villa'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'organization')},
        ),
    ]
