# Generated by Django 5.2.17 on 2026-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], default='starter', max_length=10),
        ),
    ]
