# Generated by Django 5.2.17 on 2026-09-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_migrate_role_to_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
    ]
